/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Sabin Andrei
 *
 * robot.c - the student-facing wrapper.
 *
 * This is the only place that knows:
 *   - which physical motor is LEFT and which is RIGHT;
 *   - that the lower layer is called HbridgeSpeed();
 *   - which CTIMER channels and direction GPIOs the shield uses.
 *
 * Students do not edit this file in Workshop 1.
 */

#include "robot.h"

#include "board.h"
#include "app.h"
#include "peripherals.h"
#include "pin_mux.h"
#include "hbridge.h"
#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_debug_console.h"

#ifndef SystemCoreClock
extern uint32_t SystemCoreClock;
#endif

/*
 * Physical motor mapping.
 *
 * The upstream project wires the H-bridge as:
 *     motor 1 (speed1) -> RIGHT wheel, direction GPIO0.24, PWM CT0_MAT1 / P0_25
 *     motor 2 (speed2) -> LEFT  wheel, direction GPIO0.27, PWM CT0_MAT2 / P0_26
 *
 * VERIFY THIS ON YOUR ROBOT ONCE, with the drive wheels lifted off the table:
 *
 *     motors_set(30, 0);   -> only the LEFT wheel must turn, forwards
 *     motors_set(0, 30);   -> only the RIGHT wheel must turn, forwards
 *
 * If a wheel spins the wrong way, flip its INVERT flag.
 * If the wrong wheel spins, set ROBOT_SWAP_MOTORS to 1.
 * Fix it here, once. Students must never compensate in their own code.
 */
#define ROBOT_SWAP_MOTORS   0
#define ROBOT_INVERT_LEFT   0
#define ROBOT_INVERT_RIGHT  0

/*
 * Sensor bar normalisation.
 *
 * The shield digitises the eight infrared sensors through LM339
 * comparators, and both the polarity and the physical order depend on how
 * the bar is wired and mounted. sensors_read() hides that, so student code
 * always sees "bit 0 is the leftmost sensor, 1 means it is over the line".
 *
 * VERIFY BOTH ON YOUR ROBOT ONCE, before Workshop 3. Hold the robot over
 * the track and call sensors_print() in a loop:
 *
 *   - Off the line entirely, every bit should read 0. If they all read 1,
 *     set SENSORS_ACTIVE_LOW to 1.
 *
 *   - Slide the robot so the line sits under its far LEFT sensor. The
 *     leftmost printed digit should be the 1. If the 1 appears at the
 *     right-hand end instead, set SENSORS_REVERSED to 1.
 *
 * Fix it here, once. Students must never compensate in their own code.
 */
#define SENSORS_ACTIVE_LOW  0
#define SENSORS_REVERSED    0

static int clamp_speed(int v)
{
    if (v >  100) return  100;
    if (v < -100) return -100;
    return v;
}

void robot_init(void)
{
    BOARD_InitHardware();
    BOARD_InitBootPins();
    BOARD_InitBootPeripherals();

    HbridgeInit(&g_hbridge,
                CTIMER0_PERIPHERAL,
                CTIMER0_PWM_PERIOD_CH,
                CTIMER0_PWM_1_CHANNEL,
                CTIMER0_PWM_2_CHANNEL,
                GPIO0, 24U,   /* motor 1 direction */
                GPIO0, 27U);  /* motor 2 direction */

    /* Let the supply settle, then guarantee we are stopped. */
    wait_ms(100);
    motors_stop();
}

void motors_set(int left, int right)
{
    int16_t motor1;  /* right wheel, unless ROBOT_SWAP_MOTORS */
    int16_t motor2;  /* left wheel,  unless ROBOT_SWAP_MOTORS */

    left  = clamp_speed(left);
    right = clamp_speed(right);

#if ROBOT_INVERT_LEFT
    left = -left;
#endif
#if ROBOT_INVERT_RIGHT
    right = -right;
#endif

#if ROBOT_SWAP_MOTORS
    motor1 = (int16_t)left;
    motor2 = (int16_t)right;
#else
    motor1 = (int16_t)right;
    motor2 = (int16_t)left;
#endif

    HbridgeSpeed(&g_hbridge, motor1, motor2);
}

void motors_stop(void)
{
    motors_set(0, 0);
}

void wait_ms(uint32_t ms)
{
    SDK_DelayAtLeastUs(ms * 1000U, SystemCoreClock);
}

/*
 * Raw sensor bits, exactly as the pins read: bit 0 is S10, bit 7 is S17.
 * No polarity or ordering fix-ups yet - that is sensors_read()'s job.
 */
static uint8_t sensors_raw(void)
{
    uint8_t bits = 0U;

    if (GPIO_PinRead(BOARD_INITPINS_S10_GPIO, BOARD_INITPINS_S10_GPIO_PIN)) bits |= (1U << 0);
    if (GPIO_PinRead(BOARD_INITPINS_S11_GPIO, BOARD_INITPINS_S11_GPIO_PIN)) bits |= (1U << 1);
    if (GPIO_PinRead(BOARD_INITPINS_S12_GPIO, BOARD_INITPINS_S12_GPIO_PIN)) bits |= (1U << 2);
    if (GPIO_PinRead(BOARD_INITPINS_S13_GPIO, BOARD_INITPINS_S13_GPIO_PIN)) bits |= (1U << 3);
    if (GPIO_PinRead(BOARD_INITPINS_S14_GPIO, BOARD_INITPINS_S14_GPIO_PIN)) bits |= (1U << 4);
    if (GPIO_PinRead(BOARD_INITPINS_S15_GPIO, BOARD_INITPINS_S15_GPIO_PIN)) bits |= (1U << 5);
    if (GPIO_PinRead(BOARD_INITPINS_S16_GPIO, BOARD_INITPINS_S16_GPIO_PIN)) bits |= (1U << 6);
    if (GPIO_PinRead(BOARD_INITPINS_S17_GPIO, BOARD_INITPINS_S17_GPIO_PIN)) bits |= (1U << 7);

    return bits;
}

uint8_t sensors_read(void)
{
    uint8_t bits = sensors_raw();

#if SENSORS_ACTIVE_LOW
    /* Comparators pull low over the line: flip so 1 always means "line". */
    bits = (uint8_t)(~bits);
#endif

#if SENSORS_REVERSED
    /* The bar is mounted the other way round: reverse the bit order so
     * bit 0 is the leftmost sensor again. */
    {
        uint8_t swapped = 0U;
        int     i;

        for (i = 0; i < 8; i++)
        {
            if (bits & (uint8_t)(1U << i))
            {
                swapped |= (uint8_t)(1U << (7 - i));
            }
        }

        bits = swapped;
    }
#endif

    return bits;
}

void sensors_print(void)
{
    uint8_t bits = sensors_read();
    int     i;

    /* Leftmost sensor first, so the screen matches the robot. */
    PRINTF("S = ");
    for (i = 0; i < 8; i++)
    {
        PRINTF("%d", (bits >> i) & 1U);
    }
    PRINTF("\r\n");
}
