/*
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2026 Sabin Andrei
 *
 * robot.c - the student-facing wrapper.
 *
 * This is the only place that knows:
 *   - which physical motor is LEFT and which is RIGHT;
 *   - that the lower layer is called HbridgeSpeed();
 *   - which CTIMER channels and direction GPIOs the shield uses.
 *
 * Students do not edit this file in Workshop 1.
 */

#include "robot.h"

#include "board.h"
#include "peripherals.h"
#include "pin_mux.h"
#include "hbridge.h"
#include "fsl_common.h"

#ifndef SystemCoreClock
extern uint32_t SystemCoreClock;
#endif

/*
 * Physical motor mapping.
 *
 * The upstream project wires the H-bridge as:
 *     motor 1 (speed1) -> RIGHT wheel, direction GPIO0.24, PWM CT0_MAT1 / P0_25
 *     motor 2 (speed2) -> LEFT  wheel, direction GPIO0.27, PWM CT0_MAT2 / P0_26
 *
 * VERIFY THIS ON YOUR ROBOT ONCE, with the drive wheels lifted off the table:
 *
 *     motors_set(30, 0);   -> only the LEFT wheel must turn, forwards
 *     motors_set(0, 30);   -> only the RIGHT wheel must turn, forwards
 *
 * If a wheel spins the wrong way, flip its INVERT flag.
 * If the wrong wheel spins, set ROBOT_SWAP_MOTORS to 1.
 * Fix it here, once. Students must never compensate in their own code.
 */
#define ROBOT_SWAP_MOTORS   0
#define ROBOT_INVERT_LEFT   0
#define ROBOT_INVERT_RIGHT  0

static int clamp_speed(int v)
{
    if (v >  100) return  100;
    if (v < -100) return -100;
    return v;
}

void robot_init(void)
{
    BOARD_InitHardware();
    BOARD_InitBootPins();
    BOARD_InitBootPeripherals();

    HbridgeInit(&g_hbridge,
                CTIMER0_PERIPHERAL,
                CTIMER0_PWM_PERIOD_CH,
                CTIMER0_PWM_1_CHANNEL,
                CTIMER0_PWM_2_CHANNEL,
                GPIO0, 24U,   /* motor 1 direction */
                GPIO0, 27U);  /* motor 2 direction */

    /* Let the supply settle, then guarantee we are stopped. */
    wait_ms(100);
    motors_stop();
}

void motors_set(int left, int right)
{
    int16_t motor1;  /* right wheel, unless ROBOT_SWAP_MOTORS */
    int16_t motor2;  /* left wheel,  unless ROBOT_SWAP_MOTORS */

    left  = clamp_speed(left);
    right = clamp_speed(right);

#if ROBOT_INVERT_LEFT
    left = -left;
#endif
#if ROBOT_INVERT_RIGHT
    right = -right;
#endif

#if ROBOT_SWAP_MOTORS
    motor1 = (int16_t)left;
    motor2 = (int16_t)right;
#else
    motor1 = (int16_t)right;
    motor2 = (int16_t)left;
#endif

    HbridgeSpeed(&g_hbridge, motor1, motor2);
}

void motors_stop(void)
{
    motors_set(0, 0);
}

void wait_ms(uint32_t ms)
{
    SDK_DelayAtLeastUs(ms * 1000U, SystemCoreClock);
}
